#remote_theme: fluidpixel/freelancer-theme

theme: jekyll-theme-cayman

# Site Settings
title: Rocky Foot and Ankle Surgery
description: >
  Dr Ruth Varrall MBBS FRCS
  Consultant Orthopaedic Foot and Ankle Surgeon

# Footer settings
footer:
  copyright: Dr. Ruth Varrall
  location: address
  social: DrRuthy

# Postal address (add as many lines as necessary)
address:
  - line: Rockhampton Base Hospital
  - line: QLD

collections:
  conditions:
      output: true