#remote_theme: fluidpixel/freelancer-theme

theme: jekyll-theme-cayman

# Site Settings
site:
  title: Rocky Foot and Ankle
  description: Ruth Varrall Orthopeadic Surgeon

# Footer settings
footer:
  copyright: Dr. Ruth Varrall
  location: address
  social: DrRuthy

# Postal address (add as many lines as necessary)
address:
  - line: Rockhampton Base Hospital
  - line: QLD
